In [11]:
import pandas as pd

In [13]:
import numpy as np

In [15]:
data = np.random.randn(4,3)

In [17]:
data

array([[-1.59247226, -1.41652579, -0.05894389],
       [-0.85684782, -0.74124235, -0.68485641],
       [-0.62896111, -0.83305815, -0.17652116],
       [-0.37680655, -0.26773496,  1.09974627]])

In [21]:
#data_frame = pd.Series(data)
#Series tek boyutlu dataları tutar

In [23]:
data_frame = pd.DataFrame(data)

In [25]:
data_frame

          0         1         2
0 -1.592472 -1.416526 -0.058944
1 -0.856848 -0.741242 -0.684856
2 -0.628961 -0.833058 -0.176521
3 -0.376807 -0.267735  1.099746

In [27]:
type(data_frame)

pandas.core.frame.DataFrame

In [29]:
type(data_frame[0])

pandas.core.series.Series

In [31]:
new_df = pd.DataFrame(data,index = ["Sevval","Demir","Guzel","Dilan"],columns= ["Salary","Age","Seniority"])

In [33]:
new_df

          Salary       Age  Seniority
Sevval -1.592472 -1.416526  -0.058944
Demir  -0.856848 -0.741242  -0.684856
Guzel  -0.628961 -0.833058  -0.176521
Dilan  -0.376807 -0.267735   1.099746

In [35]:
new_df["Age"]

Sevval   -1.416526
Demir    -0.741242
Guzel    -0.833058
Dilan    -0.267735
Name: Age, dtype: float64

In [37]:
new_df[["Age","Salary"]]

             Age    Salary
Sevval -1.416526 -1.592472
Demir  -0.741242 -0.856848
Guzel  -0.833058 -0.628961
Dilan  -0.267735 -0.376807

In [41]:
new_df.loc["Sevval"]

Salary      -1.592472
Age         -1.416526
Seniority   -0.058944
Name: Sevval, dtype: float64

In [43]:
new_df.iloc[0]

Salary      -1.592472
Age         -1.416526
Seniority   -0.058944
Name: Sevval, dtype: float64

In [45]:
new_df

          Salary       Age  Seniority
Sevval -1.592472 -1.416526  -0.058944
Demir  -0.856848 -0.741242  -0.684856
Guzel  -0.628961 -0.833058  -0.176521
Dilan  -0.376807 -0.267735   1.099746

In [49]:
new_df.iloc[:,1]
# : bütün rowları seçeer sonraki sayıda hangi sütun olacağını söyler

Sevval   -1.416526
Demir    -0.741242
Guzel    -0.833058
Dilan    -0.267735
Name: Age, dtype: float64

In [53]:
new_df["Extra"] = 10

In [55]:
new_df

          Salary       Age  Seniority  Extra
Sevval -1.592472 -1.416526  -0.058944     10
Demir  -0.856848 -0.741242  -0.684856     10
Guzel  -0.628961 -0.833058  -0.176521     10
Dilan  -0.376807 -0.267735   1.099746     10

In [57]:
new_df.drop("Extra",axis = 1)

          Salary       Age  Seniority
Sevval -1.592472 -1.416526  -0.058944
Demir  -0.856848 -0.741242  -0.684856
Guzel  -0.628961 -0.833058  -0.176521
Dilan  -0.376807 -0.267735   1.099746

In [59]:
new_df

          Salary       Age  Seniority  Extra
Sevval -1.592472 -1.416526  -0.058944     10
Demir  -0.856848 -0.741242  -0.684856     10
Guzel  -0.628961 -0.833058  -0.176521     10
Dilan  -0.376807 -0.267735   1.099746     10

In [61]:
new_df.drop("Extra",axis = 1,inplace =True)

In [63]:
new_df

          Salary       Age  Seniority
Sevval -1.592472 -1.416526  -0.058944
Demir  -0.856848 -0.741242  -0.684856
Guzel  -0.628961 -0.833058  -0.176521
Dilan  -0.376807 -0.267735   1.099746

In [65]:
new_df["Mehmet"] = 10

In [67]:
new_df

          Salary       Age  Seniority  Mehmet
Sevval -1.592472 -1.416526  -0.058944      10
Demir  -0.856848 -0.741242  -0.684856      10
Guzel  -0.628961 -0.833058  -0.176521      10
Dilan  -0.376807 -0.267735   1.099746      10

In [71]:
new_df.drop("Demir")

          Salary       Age  Seniority  Mehmet
Sevval -1.592472 -1.416526  -0.058944      10
Guzel  -0.628961 -0.833058  -0.176521      10
Dilan  -0.376807 -0.267735   1.099746      10

In [73]:
new_df

          Salary       Age  Seniority  Mehmet
Sevval -1.592472 -1.416526  -0.058944      10
Demir  -0.856848 -0.741242  -0.684856      10
Guzel  -0.628961 -0.833058  -0.176521      10
Dilan  -0.376807 -0.267735   1.099746      10

In [77]:
#axis = 0 olursa satır , axis = 1 olduğu için sütun yönü
new_df.drop("Mehmet",axis = 1,inplace=True)

In [79]:
new_df.loc["Sevval"]

Salary      -1.592472
Age         -1.416526
Seniority   -0.058944
Name: Sevval, dtype: float64

In [81]:
new_df.loc["Sevval"]["Salary"]

-1.5924722557743032

In [85]:
new_df.loc["Sevval","Salary"]

-1.5924722557743032

In [87]:
new_df.loc["Sevval","Salary"] = 150

In [89]:
new_df

            Salary       Age  Seniority
Sevval  150.000000 -1.416526  -0.058944
Demir    -0.856848 -0.741242  -0.684856
Guzel    -0.628961 -0.833058  -0.176521
Dilan    -0.376807 -0.267735   1.099746

In [91]:
new_df > 0

        Salary    Age  Seniority
Sevval    True  False      False
Demir    False  False      False
Guzel    False  False      False
Dilan    False  False       True

In [93]:
boolean_frame = new_df > 0

In [95]:
new_df[boolean_frame]

        Salary  Age  Seniority
Sevval   150.0  NaN        NaN
Demir      NaN  NaN        NaN
Guzel      NaN  NaN        NaN
Dilan      NaN  NaN   1.099746

In [97]:
new_df[new_df > 0]

        Salary  Age  Seniority
Sevval   150.0  NaN        NaN
Demir      NaN  NaN        NaN
Guzel      NaN  NaN        NaN
Dilan      NaN  NaN   1.099746

In [99]:
new_df[new_df["Salary"] > 1]

        Salary       Age  Seniority
Sevval   150.0 -1.416526  -0.058944

In [101]:
new_df.reset_index()

    index      Salary       Age  Seniority
0  Sevval  150.000000 -1.416526  -0.058944
1   Demir   -0.856848 -0.741242  -0.684856
2   Guzel   -0.628961 -0.833058  -0.176521
3   Dilan   -0.376807 -0.267735   1.099746

In [103]:
reset_frame = new_df.reset_index()

In [105]:
reset_frame

    index      Salary       Age  Seniority
0  Sevval  150.000000 -1.416526  -0.058944
1   Demir   -0.856848 -0.741242  -0.684856
2   Guzel   -0.628961 -0.833058  -0.176521
3   Dilan   -0.376807 -0.267735   1.099746

In [107]:
reset_frame.loc[0]

index          Sevval
Salary          150.0
Age         -1.416526
Seniority   -0.058944
Name: 0, dtype: object

In [109]:
reset_frame.iloc[0]

index          Sevval
Salary          150.0
Age         -1.416526
Seniority   -0.058944
Name: 0, dtype: object

In [113]:
new_indices = ["Sev","Dem","Guz","Dil"]

In [115]:
new_df["NewIndex"]= new_indices

In [117]:
new_df

            Salary       Age  Seniority NewIndex
Sevval  150.000000 -1.416526  -0.058944      Sev
Demir    -0.856848 -0.741242  -0.684856      Dem
Guzel    -0.628961 -0.833058  -0.176521      Guz
Dilan    -0.376807 -0.267735   1.099746      Dil

In [119]:
new_df.set_index("NewIndex",inplace=True)

In [121]:
new_df

              Salary       Age  Seniority
NewIndex
Sev       150.000000 -1.416526  -0.058944
Dem        -0.856848 -0.741242  -0.684856
Guz        -0.628961 -0.833058  -0.176521
Dil        -0.376807 -0.267735   1.099746

In [123]:
new_df.loc["Sev"]

Salary       150.000000
Age           -1.416526
Seniority     -0.058944
Name: Sev, dtype: float64

In [125]:
# multi index

In [127]:
first_index = ["Simpson","Simpson","Simpson","South Park","South Park","South Park"]

In [129]:
inner_index = ["Homer","Bart","Marge","Cartman","Kenny","Kyle"]

In [131]:
zipped_index = list(zip(first_index,inner_index))

In [133]:
zipped_index

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [135]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index)

In [137]:
zipped_index

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [139]:
sample_values = np.ones((6,2))

In [141]:
big_df = pd.DataFrame(sample_values,index=zipped_index,columns=["Age","Salary"])

In [143]:
big_df

                    Age  Salary
Simpson    Homer    1.0     1.0
           Bart     1.0     1.0
           Marge    1.0     1.0
South Park Cartman  1.0     1.0
           Kenny    1.0     1.0
           Kyle     1.0     1.0

In [145]:
big_df["Age"]

Simpson     Homer      1.0
            Bart       1.0
            Marge      1.0
South Park  Cartman    1.0
            Kenny      1.0
            Kyle       1.0
Name: Age, dtype: float64

In [147]:
big_df.loc["Simpson"].loc["Homer"]

Age       1.0
Salary    1.0
Name: Homer, dtype: float64